### ISSUE TITLE
Lab Create a Custom Skill for Azure AI Search - Function Deployment Failure

### ISSUE THREAD

**Issue by SkillableJM** [MicrosoftLearning/mslearn-knowledge-mining#54]
Lab: Create a Custom Skill for Azure AI Search
Task: Create an Azure Function for a custom skill
Step: 1. In the Azure Portal, on the Home page, create a new Function App resource with the following settings:

![image](https://github.com/user-attachments/assets/8b280dd8-06dc-4016-a1ec-59a2f45718e3)

We have users reporting that they are unable to create a function app in the Azure portal due to region limitations. I have been able to reproduce this issue when deploying the function app in East US. Users can work around this issue by deploying the function app in a different region than East US. I was able to deploy the function app within Central US without any issues.

Attached is the error json.

![image](https://github.com/user-attachments/assets/4853246d-4b8d-4dfc-ba92-4839254f7a0f)

[FunctionAppError.json](https://github.com/user-attachments/files/17836876/FunctionAppError.json)

**Comment by Skillable-Dev-Ap** [comment]
This issue has been addressed and students launching the should only be able to launch in regions with no limitations to whats needed for the purpose of this lab.

**Comment by jjelosua** [comment]
I am still facing issues while creating a Function App: "{"code":"InvalidTemplateDeployment","details":[{"code":"RequestDisallowedByPolicy","target":"FunctionApp46344302","message":"Resource 'FunctionApp46344302' was disallowed by policy. Policy identifiers: '[{\"policyAssignment\":{\"name\":\"ai102_LP5_V1*\",\"id\":\"/providers/Microsoft.Management/managementGroups/lod-org-363-pool-729-lab154265/providers/Microsoft.Authorization/policyAssignments/policyAssignment2735\"},\"policyDefinition\":{\"name\":\"ai102_LP5_V1*\",\"id\":\"/providers/Microsoft.Management/managementGroups/lod-org-363-pool-729-lab154265/providers/Microsoft.Authorization/policyDefinitions/policy2735\"}}]'.","additionalInfo":[{"type":"PolicyViolation","info":{"evaluationDetails":{"evaluatedExpressions":[{"result":"False","expressionKind":"Field","expression":"type","path":"type","expressionValue":"Microsoft.Web/sites","targetValue":"Microsoft.web/serverfarms","operator":"Equals"},{"result":"False","expressionKind":"Field","expression":"id","path":"id","expressionValue":"/subscriptions/4ce44305-7594-411f-ad28-b939b6978b7a/resourceGroups/ai102lab12/providers/Microsoft.Web/sites/FunctionApp46344302","targetValue":"/resourceGroups/ResourceGroup1/","operator":"Contains"},{"result":"False","expressionKind":"Field","expression":"type","path":"type","expressionValue":"Microsoft.Web/sites","targetValue":"Microsoft.AlertsManagement/smartDetectorAlertRules","operator":"Contains"},{"result":"False","expressionKind":"Field","expression":"type","path":"type","expressionValue":"Microsoft.Web/sites","targetValue":"Microsoft.BotService/botServices","operator":"Contains"},{"result":"False","expressionKind":"Field","expression":"type","path":"type","expressionValue":"Microsoft.Web/sites","targetValue":"Microsoft.CognitiveServices/accounts","operator":"Contains"},{"result":"False","expressionKind":"Field","expression":"type","path":"type","expressionValue":"Microsoft.Web/sites","targetValue":"Microsoft.ManagedIdentity/userAssignedIdentities","operator":"Contains"},{"result":"False","expressionKind":"Field","expression":"type","path":"type","expressionValue":"Microsoft.Web/sites","targetValue":"Microsoft.OperationalInsights/workspaces","operator":"Contains"},{"result":"False","expressionKind":"Field","expression":"type","path":"type","expressionValue":"Microsoft.Web/sites","targetValue":"Microsoft.Insights/ActionGroups","operator":"Contains"},{"result":"False","expressionKind":"Field","expression":"type","path":"type","expressionValue":"Microsoft.Web/sites","targetValue":"microsoft.insights/components","operator":"Contains"},{"result":"False","expressionKind":"Field","expression":"type","path":"type","expressionValue":"Microsoft.Web/sites","targetValue":"Microsoft.Search/searchServices","operator":"Contains"},{"result":"False","expressionKind":"Field","expression":"type","path":"type","expressionValue":"Microsoft.Web/sites","targetValue":"Microsoft.Storage/storageAccounts","operator":"Contains"}]},"policyDefinitionId":"/providers/Microsoft.Management/managementGroups/lod-org-363-pool-729-lab154265/providers/Microsoft.Authorization/policyDefinitions/policy2735","policyDefinitionName":"policy2735","policyDefinitionDisplayName":"ai102_LP5_V1*","policyDefinitionEffect":"deny","policyAssignmentId":"/providers/Microsoft.Management/managementGroups/lod-org-363-pool-729-lab154265/providers/Microsoft.Authorization/policyAssignments/policyAssignment2735","policyAssignmentName":"policyAssignment2735","policyAssignmentDisplayName":"ai102_LP5_V1*","policyAssignmentScope":"/providers/Microsoft.Management/managementGroups/lod-org-363-pool-729-lab154265","policyAssignmentParameters":{},"policyExemptionIds":[]}}]}],"message":"The template deployment failed with multiple errors. Please see details for more information."}"

**Comment by afelix-95** [comment]
In the next PR, a note will be added in the instructions clarifying that the region for the Function App resource can be changed in case of quota limitations.
